/**
 * Product Types - Laravel Backend Compatible
 * Updated to match Laravel backend structure
 */

import type { Category } from '@/features/categories/types';
import type { StockMovement } from './stock-movement.types';

/**
 * Product entity
 * Matches Laravel backend structure with ID transformations
 */
export interface Product {
  // IDs (transformed from Laravel numbers to strings)
  id: string;
  category_id: string;                    // Renamed from categoryId
  
  // Core fields
  name: string;
  slug: string;                           // NEW - Auto-generated by backend
  brand: string | null;                   // Renamed from "marca"
  description: string | null;
  sku: string | null;                     // NEW - Unique product code
  
  // Pricing & Stock
  price: number;                          // decimal(10,2) in backend
  stock: number;
  
  // Media
  image_url: string | null;               // Renamed from "image"
  
  // Status
  status: ProductStatus;
  is_featured: boolean;                   // Renamed from isFeatured
  
  // Soft delete
  deleted_at: string | null;              // NEW - For recycle bin
  
  // Timestamps
  created_at: string;                     // Renamed from createdAt
  updated_at: string;                     // NEW
  
  // Eager loaded relations (optional)
  category?: Category;                    // NEW - Full category object
  stock_movements?: StockMovement[];      // NEW - Stock history
  stock_movements_count?: number;         // NEW - Movement counter
}

/**
 * Product status enum
 */
export type ProductStatus = 'active' | 'inactive' | 'out_of_stock';

/**
 * DTO for creating a new product
 */
export interface CreateProductDto {
  name: string;
  category_id: string;
  brand?: string | null;
  description?: string | null;
  sku?: string | null;
  price: number;
  stock: number;
  image?: File;                           // For upload
  status: ProductStatus;
  is_featured?: boolean;
}

/**
 * DTO for updating an existing product
 */
export interface UpdateProductDto extends Partial<CreateProductDto> {}

/**
 * Filters for product queries
 */
export interface ProductFilters {
  category_id?: string;
  brand?: string;
  status?: ProductStatus;
  featured?: boolean;
  search?: string;
  in_stock?: boolean;
  min_price?: number;
  max_price?: number;
  sort?: 'created_at' | 'name' | 'price' | 'stock' | 'brand';
  order?: 'asc' | 'desc';
  page?: number;
  per_page?: number;
}
